services:
  nginx:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - appnet

  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: production
      APP_DEBUG: "false"
      # .env はLaravelが読む（ここは最低限でOK）
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - appnet

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - prod-mysql:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-p${DB_PASSWORD:-password}",
        ]
      retries: 10
      timeout: 5s
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  prod-mysql:
    driver: local
